<?php
return[
	'app\components\Controller'                             => BASEPATH.'app/components/controller.php',
	'app\components\AController'                            => BASEPATH.'app/components/aController.php',
	'app\components\Admin'                                  => BASEPATH.'app/components/admin.php',
	'app\controllers\HandlerController'                     => BASEPATH.'app/controllers/handlerController.php',
	'app\controllers\FormController'                        => BASEPATH.'app/controllers/formController.php',
	'app\controllers\RequestController'                     => BASEPATH.'app/controllers/requestController.php',
	'app\controllers\AdminController'                       => BASEPATH.'app/controllers/adminController.php',
	'app\controllers\CaptchaController'                     => BASEPATH.'app/controllers/captchaController.php',
	'app\models\FormModel'                                  => BASEPATH.'app/models/formModel.php',
	'app\models\LoginModel'                                 => BASEPATH.'app/models/loginModel.php',
	'app\models\ContactModel'                               => BASEPATH.'app/models/contactModel.php',
       'app\models\admin\UserModel'                            => BASEPATH.'app/models/admin/userModel.php',
       'app\models\admin\FormModel'                            => BASEPATH.'app/models/admin/formModel.php',
       'app\models\admin\DescModel'                            => BASEPATH.'app/models/admin/descModel.php',
       'app\models\admin\ModuleModel'                          => BASEPATH.'app/models/admin/moduleModel.php',
       'app\models\admin\SearchModel'                          => BASEPATH.'app/models/admin/searchModel.php',
       'app\models\admin\OptionModel'                          => BASEPATH.'app/models/admin/optionModel.php',
	'app\components\modules\Payment'                        => BASEPATH.'app/components/modules/payment.php',
	'app\components\modules\Notify'                         => BASEPATH.'app/components/modules/notify.php',
	'app\components\modules\notify\Email'                   => BASEPATH.'app/components/modules/notify/email.php',
       'app\components\modules\notify\Novinpayamak'            => BASEPATH.'app/components/modules/notify/novinpayamak.php',
	'app\components\modules\payment\Zarinpal'               => BASEPATH.'app/components/modules/payment/zarinpal.php',
];