<?php
return [
	'framework\autoloader\Autoloader' => FRAMEWORK.'autoloader/autoloader.php',
	'framework\autoloader\exception\AutoloaderException' => FRAMEWORK.'autoloader/exception/autoloaderException.php',
	'framework\core\Router' => FRAMEWORK.'core/router.php',
	'framework\core\exception\RouterException' => FRAMEWORK.'core/exception/routerException.php',
	'framework\core\Controller' => FRAMEWORK.'core/controller.php',
	'framework\core\exception\ControllerException' => FRAMEWORK.'core/exception/controllerException.php',
	'framework\core\Config' => FRAMEWORK.'core/config.php',
	'framework\core\exception\ConfigException' => FRAMEWORK.'core/exception/configException.php',
	'framework\helpers\File' => FRAMEWORK.'helpers/file.php',
	'framework\helpers\exception\FileException' => FRAMEWORK.'helpers/exception/fileException.php',
	'framework\helpers\Html' => FRAMEWORK.'helpers/html.php',
	'framework\helpers\exception\HtmlException' => FRAMEWORK.'helpers/exception/htmlException.php',
	'framework\log\Log' => FRAMEWORK.'log/log.php',
	'framework\log\exception\LogException' => FRAMEWORK.'log/exception/logException.php',
	'framework\request\Request' => FRAMEWORK.'request/request.php',
	'framework\request\exception\RequestException' => FRAMEWORK.'request/exception/requestException.php',
	'framework\session\Session' => FRAMEWORK.'session/session.php',
	'framework\session\exception\SessionException' => FRAMEWORK.'session/exception/sessionException.php',
	'framework\security\Csrf' => FRAMEWORK.'security/csrf.php',
	'framework\security\exception\CsrfException' => FRAMEWORK.'security/exception/csrfException.php',
	'framework\validator\Validator' => FRAMEWORK.'validator/validator.php',
	'framework\validator\exception\ValidatorException' => FRAMEWORK.'validator/exception/validatorException.php',
	'framework\database\Database' => FRAMEWORK.'database/database.php',
	'framework\database\exception\DatabaseException' => FRAMEWORK.'database/exception/databaseException.php',
	'framework\database\QueryBuilder' => FRAMEWORK.'database/queryBuilder.php',
	'framework\database\exception\QueryBuilderException' => FRAMEWORK.'database/exception/queryBuilderException.php',
	'framework\pagination\Pagination' => FRAMEWORK.'pagination/pagination.php',
	'framework\pagination\exception\PaginationException' => FRAMEWORK.'pagination/exception/paginationException.php',
	'framework\session\FlashMessage' => FRAMEWORK.'session/flashMessage.php',
	'framework\helpers\ArrayHelper' => FRAMEWORK.'helpers/arrayHelper.php',
	'framework\helpers\exception\ArrayHelperException' => FRAMEWORK.'helpers/exception/arrayHelperException.php',
	'framework\core\Model' => FRAMEWORK.'core/model.php',
	'framework\core\exception\ModelException' => FRAMEWORK.'core/exception/modelException.php',
	'framework\captcha\Captcha' => FRAMEWORK.'captcha/captcha.php',
	'framework\captcha\exception\CaptchaException' => FRAMEWORK.'captcha/exception/captchaException.php',
];